In [2]:
import torch

In [4]:
torch.empty(1)

tensor([1.1367e+24])

In [6]:
torch.empty(3)

tensor([2.0401e-33, 0.0000e+00, 1.2542e+27])

In [8]:
torch.empty(1)

tensor([1.2132e-38])

In [10]:
torch.rand(1)

tensor([0.2005])

In [12]:
torch.rand(1)

tensor([0.6562])

In [14]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [16]:
x = torch.rand(4, 4)
x

tensor([[0.8842, 0.8186, 0.6757, 0.4737],
        [0.4289, 0.2624, 0.1343, 0.8511],
        [0.0851, 0.1047, 0.2097, 0.4449],
        [0.2003, 0.7105, 0.5470, 0.3468]])

In [18]:
x.view(16)

tensor([0.8842, 0.8186, 0.6757, 0.4737, 0.4289, 0.2624, 0.1343, 0.8511, 0.0851,
        0.1047, 0.2097, 0.4449, 0.2003, 0.7105, 0.5470, 0.3468])

In [20]:
x.shape

torch.Size([4, 4])

In [22]:
x.view(-1, 8)

tensor([[0.8842, 0.8186, 0.6757, 0.4737, 0.4289, 0.2624, 0.1343, 0.8511],
        [0.0851, 0.1047, 0.2097, 0.4449, 0.2003, 0.7105, 0.5470, 0.3468]])

In [24]:
x.size()

torch.Size([4, 4])

In [26]:
import numpy as np

In [28]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [30]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [32]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [34]:
a

tensor([2., 2., 2., 2., 2.])

In [36]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [38]:
a.add(1)

tensor([3., 3., 3., 3., 3.])

In [40]:
a

tensor([2., 2., 2., 2., 2.])

In [42]:
b = b + 1
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [44]:
a

tensor([2., 2., 2., 2., 2.])

In [46]:
a.add_(11)

tensor([13., 13., 13., 13., 13.])

In [48]:
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [64]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y + 2
z = z.mean()
print(z)
z.backward()
print(x.grad)

tensor([ 0.2090, -0.0223,  0.8394], requires_grad=True)
tensor([2.2090, 1.9777, 2.8394], grad_fn=<AddBackward0>)
tensor(7.6177, grad_fn=<MeanBackward0>)
tensor([1.4726, 1.3185, 1.8929])


tensor([-0.6518, -1.3006,  0.4915], requires_grad=True)

tensor([1.3482, 0.6994, 2.4915], grad_fn=<AddBackward0>)

tensor([3.8177, 2.4892, 8.2076], grad_fn=<AddBackward0>)

RuntimeError: grad can be implicitly created only for scalar outputs