In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
age = np.array([12, 14, 40, 35, 26, 30, 30, 50, 75, 50, 30, 45, 25, 55, 28, 25, 50, 40, 25, 35])

In [11]:
age.size

20

In [13]:
age.shape

(20,)

In [15]:
np.unique(age)

array([12, 14, 25, 26, 28, 30, 35, 40, 45, 50, 55, 75])

In [17]:
np.count_nonzero(age)

20

In [19]:
np.count_nonzero(age==30)

3

In [21]:
for x in np.unique(age):
    print(x, " --> ", np.count_nonzero(age==x))

12  -->  1
14  -->  1
25  -->  3
26  -->  1
28  -->  1
30  -->  3
35  -->  2
40  -->  2
45  -->  1
50  -->  3
55  -->  1
75  -->  1


In [29]:
Xi = np.unique(age)

T = age.size

Ni = []
for x in Xi:
    Ni.append(np.count_nonzero(age==x))

Ni = np.array(Ni)

fi = Ni/T

Ncc = []
Ni_l = Ni.tolist()
Ncc.append(Ni[0])

for i in range(1, Xi.size):
    Ncc.append(Ncc[i-1]+Ni_l[i])

Ncc = np.array(Ncc)
Fcc = Ncc / T

In [31]:
Xi

array([12, 14, 25, 26, 28, 30, 35, 40, 45, 50, 55, 75])

In [33]:
Ni

array([1, 1, 3, 1, 1, 3, 2, 2, 1, 3, 1, 1])

In [35]:
T

20

In [39]:
fi

array([0.05, 0.05, 0.15, 0.05, 0.05, 0.15, 0.1 , 0.1 , 0.05, 0.15, 0.05,
       0.05])

In [41]:
Ncc

array([ 1,  2,  5,  6,  7, 10, 12, 14, 15, 18, 19, 20])