In [1]:
import numpy as np

Pour résoudre le système d’équations linéaires 3 * x0 + x1 = 9 et x0 + 2 * x1 = 8 :

In [4]:
A = np.array(
    [
        [3, 1],
        [1, 2]
    ]
)

In [6]:
A[0, 0]

3

In [8]:
A.shape

(2, 2)

In [10]:
B = np.array([
    [9],
    [8]
])

In [12]:
B.shape

(2, 1)

In [16]:
X = np.linalg.solve(A, B)

In [18]:
X

array([[2.],
       [3.]])

In [22]:
C = B.T

In [24]:
C

array([[9, 8]])

In [26]:
C.shape

(1, 2)

In [28]:
D = np.array([9, 8])

In [30]:
D.shape

(2,)

In [32]:
D

array([9, 8])

In [34]:
B

array([[9],
       [8]])

In [36]:
D.resize(2,1)

In [38]:
D.shape

(2, 1)

In [40]:
D

array([[9],
       [8]])

In [42]:
D.resize(1, 2)

In [44]:
D

array([[9, 8]])